import type { RequestOptions } from "./interface";
export const requestOptions: RequestOptions = {
  method: "POST",
  redirect: "follow",
};
export const inputConfig = {
  customerInfo: [
    {
      model: 'phone',
      type: 'text',
      placeholder: 'Phone (For Tracking Confirmation)',
      errorMessage: 'errors.phone',
      maxLength: 10,
      regex: '^[0-9]*$',
    },
    {
      model: 'email',
      type: 'email',
      placeholder: 'Email (For Order Confirmation)',
      errorMessage: 'errors.email',
      maxLength: 50, // Optional, you can omit if not needed
    }
  ],
  paymentInfo: [
    {
      model: 'cardNumber',
      type: 'text',
      placeholder: 'Card Number',
      errorMessage: 'errors.cardNumber',
      maxLength: 16,
      regex: '^[0-9]*$',
    },
    {
      model: 'expiryMonth',
      type: 'text',
      placeholder: 'MM',
      errorMessage: 'errors.expiryMonth',
      maxLength: 2,
      regex: '^[0-9]*$',
    },
    {
      model: 'expiryYear',
      type: 'text',
      placeholder: 'YYYY',
      errorMessage: 'errors.expiryYear',
      maxLength: 4,
      regex: '^[0-9]*$',
    },
    {
      model: 'cvv',
      type: 'text',
      placeholder: 'CVV Code',
      errorMessage: 'errors.cvv',
      maxLength: 4,
      regex: '^[0-9]*$',
    },
  ],
}
export const emptyCart = {
  product_id: 1,
  title: 'Your cart is empty',
  variant_id: '',
  price: 0,
  image: '/images/empty-cart.png',
  variant_title: 'Add something to make me happy :)',
  product_qty: 0,
};
export const upsellConfig = {
  offer1: {
    pageType: "upsellPage1",
    productImg: "/images/offer1/up1.webp",
    submitBtnTitle: "COMPLETE MY ORDER 👉",
    event: "Upsell1cv",
    stepCompleted: { yes: 3, no: 3 },
    nextStep: { yes: "/offer2", no: "/offer2" },
  },
  offer2: {
    pageType: "upsellPage2",
    header: "You Can't Leave Without Taking ADVANTAGE of this SPECIAL OFFER!",
    heading: "As a special thanks, we would like to offer you our 3 pack of FlexiKnee™️ - Natural Knee Pain Patches for just $39.95.",
    productImg: "/images/offer2/up2.webp",
    submitBtnTitle: "COMPLETE CHECKOUT 👉",
    event: "Purchase",
    stepCompleted: { yes: 5, no: 4 },
    nextStep: { yes: "/offer3", no: "/offer2_1" },
  },
  offer2_1: {
    pageType: "upsellPage2",
    header: "You Can't Leave Without Taking ADVANTAGE of this SPECIAL OFFER!",
    heading: "As a special thanks, we would like to offer you our 3 pack of FlexiKnee™️ - Natural Knee Pain Patches for just $19.95.",
    productImg: "/images/offer2/up2.webp",
    submitBtnTitle: "COMPLETE CHECKOUT 👉",
    event: "Purchase",
    stepCompleted: { yes: 5, no: 5 },
    nextStep: { yes: "/offer3", no: "/offer3" },
  },
  offer3: {
    pageType: "upsellPage3",
    header: "You Can't Leave Without Taking ADVANTAGE of this SPECIAL OFFER!",
    heading: "As a special thanks, we would like to offer you a pair of our Knee Relieve Pro™️ - Nano-Fiber Compression Sleeves for just $39.95/each.",
    productImg: "/images/offer3/up3.webp",
    kitPrice: [{ kit: '1 - 3 Kits', price: '19.95 each' }, { kit: '4 - 6 Kits', price: '17.95 each' }, { kit: '7 - 10 Kits', price: '12.95 each' }],
    submitBtnTitle: "COMPLETE CHECKOUT 👉",
    stepCompleted: { yes: 7, no: 6 },
    nextStep: { yes: "/thankyou", no: "/offer3_1" },
    event: "Upsell2cv"
  },
  offer3_1: {
    pageType: "upsellPage3",
    header: "You Can't Leave Without Taking ADVANTAGE of this SPECIAL OFFER!",
    heading: "As a special thanks, we would like to offer you a pair - Side Sleeper Knee Pillows for just $29.95.",
    productImg: "/images/offer3/down3.webp",
    kitPrice: [{ kit: '1 - 3 Kits', price: '14.95 each' }, { kit: '4 - 6 Kits', price: '12.95 each' }, { kit: '7 - 10 Kits', price: '10.95 each' }],
    submitBtnTitle: "COMPLETE CHECKOUT 👉",
    stepCompleted: { yes: 7, no: 7 },
    nextStep: { yes: "/thankyou", no: "/thankyou" },
    event: "Upsell2cv"
  },

}

export const rawData = [
  {
    "productId": "1546",
    "name": "1 Pack of FlexiKnee™️ - Natural Knee Pain Patches",
    "qty": "1",
    "productSku": "6WV132H",
    "actualProductId": "177",
    "replacedByOrderItemId": "",
    "variantDetailId": "",
    "title": "",
    "variantSku": "",
    "externalProductId": "8510666801416",
    "shipping": "4.95",
    "price": "17.95",
    "merchantId": "18",
    "descriptor": "EASY FIX PRODUCTS 8883512031",
    "initialSalesTax": "0.00",
    "customSalesTax": "",
    "refundRemaining": "22.90",
    "merchantTxnId": "61410",
    "purchaseStatus": "",
    "billingCycleType": "",
    "finalBillingCycle": "",
    "isPreauthVoid": "0",
    "nextBillDate": "",
    "trialEnabled": "",
    "trialType": "",
    "trialAuthType": "",
    "regularPrice": "",
    "productQty": "1",
    "cycle1_billDelay": "",
    "cycle2_price": "",
    "cycle2_shipPrice": "",
    "cycle2_isShippable": "0",
    "cycle2_billDelay": "",
    "cycle3_price": "",
    "cycle3_shipPrice": "",
    "cycle3_isShippable": "0",
    "cycle3_billDelay": "",
    "lastCustomCycle": "0",
    "purchaseCycle": "",
    "txnType": "SALE",
    "cancellationScheduled": "0",
    "cancelAfterDate": "",
    "pauseScheduled": "0",
    "billingCycleNumber": "1",
    "staggerIntervalCycles": "",
    "staggerFulfillments": "0",
    "recycleFailedStatus": "0",
    "recycleReference": "0",
    "responseType": "SUCCESS"
  },
  {
    "productId": "1461",
    "name": "Discounted Expedited Shipping",
    "qty": "1",
    "productSku": "Expedited-Shipping",
    "actualProductId": "8",
    "replacedByOrderItemId": "",
    "variantDetailId": "",
    "title": "",
    "variantSku": "",
    "externalProductId": "",
    "shipping": "0.00",
    "price": "7.95",
    "merchantId": "18",
    "descriptor": "EASY FIX PRODUCTS 8883512031",
    "initialSalesTax": "0.00",
    "customSalesTax": "",
    "refundRemaining": "7.95",
    "merchantTxnId": "73235",
    "purchaseStatus": "",
    "billingCycleType": "",
    "finalBillingCycle": "",
    "isPreauthVoid": "0",
    "nextBillDate": "",
    "trialEnabled": "",
    "trialType": "",
    "trialAuthType": "",
    "regularPrice": "",
    "productQty": "1",
    "cycle1_billDelay": "",
    "cycle2_price": "",
    "cycle2_shipPrice": "",
    "cycle2_isShippable": "0",
    "cycle2_billDelay": "",
    "cycle3_price": "",
    "cycle3_shipPrice": "",
    "cycle3_isShippable": "0",
    "cycle3_billDelay": "",
    "lastCustomCycle": "0",
    "purchaseCycle": "",
    "txnType": "SALE",
    "cancellationScheduled": "0",
    "cancelAfterDate": "",
    "pauseScheduled": "0",
    "billingCycleNumber": "1",
    "staggerIntervalCycles": "",
    "staggerFulfillments": "0",
    "recycleFailedStatus": "0",
    "recycleReference": "0",
    "responseType": "SUCCESS"
  }
];
